import frappe
from frappe import _
from frappe.utils import flt, today

@frappe.whitelist()
def get_room_billing_info(room):
    from dagaarsoft_hospitality.dagaarsoft_hospitality.utils.room_utils import get_billing_info_for_room
    return get_billing_info_for_room(room)

def on_sales_invoice_submit(doc, method=None):
    """
    FIX 5: Only post to folio when SI is a POSA/F&B invoice (has hotel_room but
    was NOT generated from folio). If SI was generated by generate_invoice(),
    its hotel_folio is already set and charges are already marked is_billed=1,
    so we must NOT post another charge.
    """
    if doc.docstatus != 1:
        return

    room       = getattr(doc, "hotel_room", None)
    folio_name = getattr(doc, "hotel_folio", None)

    # If hotel_folio is set AND all items are already marked billed in folio → skip
    # This is a folio-generated invoice, not a POSA charge
    if folio_name and frappe.db.exists("Guest Folio", folio_name):
        # Check if this SI is the folio's own invoice (generated by generate_invoice)
        folio_si = frappe.db.get_value("Guest Folio", folio_name, "sales_invoice")
        if folio_si == doc.name:
            # This is the folio invoice itself — do NOT post a charge back
            return

    # If no hotel_room, not a hotel sale — skip
    if not room:
        return

    # Try to resolve folio from room if not already set
    if not folio_name:
        try:
            from dagaarsoft_hospitality.dagaarsoft_hospitality.utils.room_utils import get_billing_info_for_room
            info = get_billing_info_for_room(room)
            doc.db_set("hotel_stay",  info.get("guest_stay"),  update_modified=False)
            doc.db_set("hotel_folio", info.get("guest_folio"), update_modified=False)
            folio_name = info.get("guest_folio")
        except Exception:
            return

    if not folio_name or not frappe.db.exists("Guest Folio", folio_name):
        return

    # FIX 5: Absolute dedup — never post same SI twice
    if frappe.db.exists("Folio Charge Line", {
            "parent": folio_name,
            "reference_doctype": "Sales Invoice",
            "reference_name": doc.name,
            "is_void": 0}):
        return

    # Determine charge category
    charge_cat = "F&B"
    if getattr(doc, "restaurant_table", None):
        charge_cat = "Restaurant"
    else:
        try:
            cfg = frappe.db.get_single_value("Hospitality Settings", "default_posa_charge_category")
            if cfg:
                charge_cat = cfg
        except Exception:
            pass

    # Post the F&B charge to folio
    try:
        from dagaarsoft_hospitality.dagaarsoft_hospitality.utils.folio_utils import post_charge_to_folio
        table = getattr(doc, "restaurant_table", "") or ""
        post_charge_to_folio(
            folio_name=folio_name,
            description="{0} - {1}{2}".format(
                charge_cat, doc.name,
                " | Table: {0}".format(table) if table else ""),
            amount=flt(doc.grand_total),
            charge_category=charge_cat,
            reference_doctype="Sales Invoice",
            reference_name=doc.name,
            qty=1, rate=flt(doc.grand_total))
        # FIX 11: Immediately update folio status
        frappe.db.set_value("Guest Folio", folio_name,
            "sales_invoice_status", doc.status, update_modified=False)
    except Exception:
        frappe.log_error(frappe.get_traceback(), "POSA Folio Post Error")


def on_sales_invoice_cancel(doc, method=None):
    try:
        cascade = frappe.db.get_single_value("Hospitality Settings",
            "cascade_cancel_linked_transactions")
    except Exception:
        cascade = 0
    if not cascade:
        return
    folio_name = getattr(doc, "hotel_folio", None)
    if not folio_name or not frappe.db.exists("Guest Folio", folio_name):
        return
    rows = frappe.get_all("Folio Charge Line",
        {"parent": folio_name, "reference_doctype": "Sales Invoice",
         "reference_name": doc.name, "is_void": 0}, ["name"])
    if not rows:
        return
    folio = frappe.get_doc("Guest Folio", folio_name)
    changed = False
    for row in folio.folio_charges:
        if row.name in {r.name for r in rows}:
            row.is_void = 1
            row.void_reason = "Auto-voided: SI {0} cancelled".format(doc.name)
            changed = True
    if changed:
        folio.save(ignore_permissions=True)
    # FIX 11: Sync status
    folio_si = frappe.db.get_value("Guest Folio", folio_name, "sales_invoice")
    if folio_si == doc.name:
        frappe.db.set_value("Guest Folio", folio_name, {
            "sales_invoice_status": "Cancelled",
            "invoice_outstanding": 0, "invoice_paid_amount": 0
        }, update_modified=False)


def on_payment_entry_submit(doc, method=None):
    folio_name = getattr(doc, "hotel_folio", None)
    if not folio_name or not frappe.db.exists("Guest Folio", folio_name):
        return
    # FIX 4/5: Dedup
    if frappe.db.exists("Folio Payment Line", {"parent": folio_name, "payment_entry": doc.name}):
        return
    folio = frappe.get_doc("Guest Folio", folio_name)
    line = folio.append("folio_payments", {})
    line.payment_date     = doc.posting_date or today()
    line.payment_mode     = doc.mode_of_payment
    line.description      = "Payment Entry - {0}".format(doc.name)
    line.amount           = flt(doc.paid_amount or doc.received_amount)
    line.reference_number = doc.reference_no
    line.payment_entry    = doc.name
    line.posted_by        = frappe.session.user
    folio.save(ignore_permissions=True)
    # FIX 11: Sync invoice status immediately
    _sync_folio_invoice_status(folio_name)


def on_payment_entry_cancel(doc, method=None):
    try:
        cascade = frappe.db.get_single_value("Hospitality Settings",
            "cascade_cancel_linked_transactions")
    except Exception:
        cascade = 0
    if not cascade:
        return
    folio_name = getattr(doc, "hotel_folio", None)
    if not folio_name or not frappe.db.exists("Guest Folio", folio_name):
        return
    folio = frappe.get_doc("Guest Folio", folio_name)
    changed = False
    for row in list(folio.folio_payments):
        if row.payment_entry == doc.name:
            folio.remove(row); changed = True
    if changed:
        folio.save(ignore_permissions=True)
    _sync_folio_invoice_status(folio_name)


def _sync_folio_invoice_status(folio_name):
    """FIX 11: Immediately sync invoice status on any payment change."""
    si = frappe.db.get_value("Guest Folio", folio_name, "sales_invoice")
    if not si:
        return
    from dagaarsoft_hospitality.dagaarsoft_hospitality.utils.billing import get_invoice_billing_status
    info = get_invoice_billing_status(si)
    frappe.db.set_value("Guest Folio", folio_name, {
        "sales_invoice_status": info.get("label", ""),
        "invoice_outstanding":  info.get("outstanding", 0),
        "invoice_paid_amount":  info.get("paid", 0),
    }, update_modified=False)
